// <auto-generated />
using DoctorClinicManagerWebApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoctorClinicManagerWebApi.Migrations
{
    [DbContext(typeof(DoctorManagerContext))]
    [Migration("20240514153903_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DoctorClinicManagerWebApi.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"), 1L, 1);

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 101,
                            Experience = 15,
                            Name = "tonny",
                            Phone = "9876543321",
                            Speciality = "Multispecialist"
                        },
                        new
                        {
                            DoctorId = 102,
                            Experience = 3,
                            Name = "stephen-strange",
                            Phone = "9988776655",
                            Speciality = "Neuro"
                        },
                        new
                        {
                            DoctorId = 103,
                            Experience = 5,
                            Name = "Bruce-Banner",
                            Phone = "2133443422",
                            Speciality = "Neuro"
                        },
                        new
                        {
                            DoctorId = 104,
                            Experience = 1,
                            Name = "peter-parker",
                            Phone = "765790809438",
                            Speciality = "Webspecialist"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
