// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductApp.Context;

#nullable disable

namespace ProductApp.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20240718160817_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductApp.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ImageUrls = "https://example.com/laptop.jpg",
                            ProductName = "Laptop",
                            ProductPrice = 999.99m
                        },
                        new
                        {
                            ProductId = 2,
                            ImageUrls = "https://example.com/smartphone.jpg",
                            ProductName = "Smartphone",
                            ProductPrice = 599.99m
                        },
                        new
                        {
                            ProductId = 3,
                            ImageUrls = "https://example.com/headphones.jpg",
                            ProductName = "Headphones",
                            ProductPrice = 149.99m
                        },
                        new
                        {
                            ProductId = 4,
                            ImageUrls = "https://example.com/tablet.jpg",
                            ProductName = "Tablet",
                            ProductPrice = 399.99m
                        },
                        new
                        {
                            ProductId = 5,
                            ImageUrls = "https://example.com/smartwatch.jpg",
                            ProductName = "Smartwatch",
                            ProductPrice = 249.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
